version: "3.7"

services:

  blog:
    build: .
    restart: always
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: 2G
    ports:
      - "5000:5000"
    working_dir: "/app"
    command: >
      bash -c "
      git fetch --all &&
      git reset --hard origin/master &&
      pip install -r requirements.txt &&
      python3 init_db.py
      flask run --host=0.0.0.0 --port=5000"